site_name: 计数学院服务器使用手册
site_description: 计数学院服务器使用手册
site_url: https://ayxy-server-tutorail.readthedocs.io/zh-cn/latest/
site_author: Jinghui Chan

repo_name: AYXY-Server-Tutorial
repo_url: https://github.com/JinghuiChan/AYXY-Server-Tutorail.git

copyright: Copyright &copy; 2024-present <a href="https://ayxy-server-tutorail.readthedocs.io/zh-cn/latest/" target="_blank" rel="noopener noreferrer">Jinghui Chan</a>

theme:
  name: material
  custom_dir: docs/overrides
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate
    - content.tabs.link
    - navigation.expand
    - navigation.path
    # - toc.integrate
    # - navigation.indexes
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.instant
    # - navigation.expand
    # - navigation.sections


  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    #annotation: material/arrow-right-circle
    annotation: material/plus-circle

extra:
  social:
    - icon: fontawesome/brands/github
      #link: https://github.com/JinghuiChan/ComputerWings

nav:
  - 服务器介绍:
      - 服务器介绍: "服务器介绍/服务器硬件以及网络.md"
  - 科研成果登记系统:
      - 项目部署: "科研成果登记系统/系统启动步骤.md"
      - 访问方式: "科研成果登记系统/访问方式.md"
  - OJ系统:
      - 访问方式: "OJ系统/访问方式.md"
      - 项目介绍:
          - 概述: "OJ系统/introducition/README.md"
          - 系统设计: "OJ系统/introducition/architecture.md"
      - 快速部署:
          - 环境配置: "OJ系统/deploy/env.md"
          - 快速部署: "OJ系统/deploy/docker.md"
          - 网站设置: "OJ系统/deploy/setting.md"
          - 开启HTTPS: "OJ系统/deploy/open-https.md"
          - 多个判题机: "OJ系统/deploy/multi-judgeserver.md"
          - 如何更新: "OJ系统/deploy/update.md"
          - 如何备份: "OJ系统/deploy/how-to-backup.md"
          - 常见问题: "OJ系统/deploy/faq.md"
      - 单体部署:
          - 单体部署①--MySQL部署: "OJ系统/monomer/mysql.md"
          - 单体部署②--MySQL更新工具: "OJ系统/monomer/mysql-checker.md"
          - 单体部署③--Redis部署: "OJ系统/monomer/redis.md"
          - 单体部署④--Nacos部署: "OJ系统/monomer/nacos.md"
          - 单体部署⑤--后端部署: "OJ系统/monomer/backend.md"
          - 单体部署⑥--判题服务部署: "OJ系统/monomer/judgeserver.md"
          - 单体部署⑦--前端部署: "OJ系统/monomer/frontend.md"
          - 单体部署⑧--评测数据同步: "OJ系统/monomer/rsync.md"
      - 开发文档:
          - 数据库说明: "OJ系统/develop/db.md"
          - 调度与评测: "OJ系统/develop/judge_dispatcher.md"
          - 安全沙盒: "OJ系统/develop/sandbox.md"
          - 后端开发文档: "OJ系统/develop/backend.md"
      - 使用文档:
          - 题目管理: "OJ系统/use/import-problem.md"
          - 判题模式: "OJ系统/use/judge-mode.md"
          - 用例模式: "OJ系统/use/judge-case-mode.md"
          - 取消评测: "OJ系统/use/cancel-judge.md"
          - 测试用例: "OJ系统/use/testcase.md"
          - 训练介绍: "OJ系统/use/training.md"
          - 比赛介绍: "OJ系统/use/contest.md"
          - 比赛滚榜: "OJ系统/use/scroll-board.md"
          - 团队介绍: "OJ系统/use/group.md"
          - 导入用户: "OJ系统/use/import-user.md"
          - 用户管理: "OJ系统/use/admin-user.md"
          - 通知和公告发布: "OJ系统/use/notice-announcement.md"
          - 评论管理: "OJ系统/use/discussion-admin.md"
          - 自定义前端: "OJ系统/use/update-fe.md"
          - 自定义题目难度: "OJ系统/use/custom-difficulty.md"
          - 取消前端免费CDN: "OJ系统/use/close-free-cdn.md"
  - seafile网盘部署:
      - 访问方式: "seafile网盘/访问方式.md"
      - 部署方式: "seafile网盘/部署Seafile.md"


#nav:
#  - 前言: "index.md"
#  - 必学工具:
#      - 翻墙: "必学工具/翻墙.md"
#      - Vim: "必学工具/Vim.md"
#      - Emacs: "必学工具/Emacs.md"
#      - Git: "必学工具/Git.md"
#      - GitHub: "必学工具/GitHub.md"
#      - "GNU Make": "必学工具/GNU_Make.md"
#      - CMake: "必学工具/CMake.md"
#      - LaTeX: "必学工具/LaTeX.md"
#      - Docker: "必学工具/Docker.md"
#      - Scoop: "必学工具/Scoop.md"
#      - 日常学习工作流: "必学工具/workflow.md"
#      - 实用工具箱: "必学工具/tools.md"
#      - 信息检索: "必学工具/信息检索.md"
#  - 好书推荐: "好书推荐.md"

markdown_extensions:
  - abbr
#pymdownx.pathconverter 网页中嵌入pdf
  - pymdownx.pathconverter:
      base_path: ' '
      relative_path: ' '
      absolute: false
      tags: 'a script img link object embed'
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - def_list
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:              #使用数学公式MathJax，需要添加config.js in file javascripts
      generic: true

# 表格具有排序功能，还需要添加tables.js
# 可以使用数学公式 MathJax ，需添加config.js
extra_javascript:
  - javascripts/tables.js
  #  - javascripts/tablesort.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - glightbox
  #页面引入pdf，点击打开pdf
  - print-site:
      enabled_if_env: ENABLE_PDF_EXPORT




# pip install mkdocs-material
# pip install mkdocs-glightbox
# pip install markdown-checklist
# pip install mkdocs-link-marker    # https://github.com/timmeinerzhagen/mkdocs-link-marker
#pip install pymdown-extensions
#pip install mkdocs-print-site-plugin


# mkdocs serve  运行